kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      auto_tag: true
      auto_tag_suffix: amd64
      repo: mazzolino/power-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: plugins/docker:linux-arm64
    settings:
      auto_tag: true
      auto_tag_suffix: arm64
      repo: mazzolino/power-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request

---
kind: pipeline
name: manifest

steps:
  - name: manifest
    image: plugins/manifest:1
    settings:
      spec: manifest.tmpl
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm64

depends_on:
  - amd64
  - arm64

---
kind: secret

external_data:
  docker_username:
    path: secret/docker
    name: username
  docker_password:
    path: secret/docker
    name: password
