version: "3.4"

services:
  app:
    build: .
    image: mazzolino/power-bot
    #volumes:
      #- .:/home/node/app
    environment:
      REDISTOGO_URL: redis://redis
    env_file: .env
    networks:
      - backend
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - backend

networks:
  backend:
